language: go
go:
- '1.7'
sudo: required
dist: trusty
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  # DOCKER_EMAIL, # DOCKER_USER, # DOCKER_PASS
  - secure: P272AtwQ580xdcM6EV15d3Jzdl0CIstv3qfqPCgeh6sHI7Y1hA0cHZP6UWW3NzjXNcUhczXjTyx1j1T+nODV+klf7qjDwwW/56qJ+WqSbKTbNWD9DOvLZBp/5zoxLPFfKPMME8P6N3Q+CGZc2HQfGau42uYVigczrZPSpzwV8dD0S/4FlWCTDZeWPrIzFlKcPT0rWERySQz8zX0vJ8pc1xkYeeLCwY/iG21/SKZ0lj5r9uuBG7UmVFj1WdZCFYHx5g+R/I/yQQLH0f5Hpt36vQPP/hklc1f4o6Jxd0pakL28UugIqsd+IjMfcnqDXCfNptWdE/+RUuzkB4VdX6LP4Ee+KwocG6qdLG5PNHCPNoHUyN0EIZOQ76rbRIGpJJ9T5eBQnvL7b9WZ2vAYnUoSL1jT9IpFCynU5PF17QMuRRmZkQcuc+ck9KmpFkTOoHtw265GuQugXzpefKkvmqbq1c/8Kfx8tGCfqX3xi8Wi2c/+hmkpSXEXeiIu1akcB/ulHUWClSBcZ5Aqn4OsuQbcI2CI1kycojsBAq+hYAhLfSd8iXt4AvNvlOMoR3hiMhkWfDSvoLtCg6+meGoUoEca+tupmyaRbj0izdb4RCsTG06iQkHTYeMB1DGy4HZsUWJVHWq2b37DD/ibAS4lOnAJcUZ/Sz1lDf2Y3Bf8CLbm8FE=
  - secure: mdTmOc+/OGlDoRUuOLJ2v6ZCqjfQibF54Ie8ZlRiaZSs+lOZLABB6+uPzuQvbVCSQX5+5N+T222BIU+Ac7AgnBtd4SO5kA63lYTqwnJOUH7d2JzaY42sdiSeRcyKJwGHTW0AlyuiriLatTaSGjB5AilmWXDevxP2cBj+x/gTSwL5h87CrWbUbc69H5JSyeRNmOCPM6nBssVFcwSNhJNDRyFatRAzPBI9kQbMoKXpXcCvqv4GeZJ4oeuHYENTyj1wEQIrMCkQhn/tGbKFWmDSVE1v/gINuXHyNdCK6DngcfTwoWm7kQ4SEZ0DHeuPzt78wCQ1yxl8ENjrnXfcF+BsB4fmPt65XflB6yfOJvcNV4jRWXLaQ8fxlOWhSgkHbPU1nh1EP3dVJeLsAYIHelmFoloXdgDPE10vdWXU189H8f1jpHp/bI+mhx1eDflET3CB3nrBK8vP/G1qYgsgH4lMQlaPJIroQmP9nhvhjGFwNW8viF+UeR6fTqy74yaIzdKBLfHx5qOji+OGJ2tXvPaaKeF6qiL4L8p9ydF+R941k7bVCTuSkVTCwrq18gutRGLQuML7AirszyrniAOqCCOTEKb3dDUSA82sxSiBK4TXG8Oy9ligRqCMU49LIxMKxA7FuK5vxfNW4D3/peZvc3Uljm6zDI1paljPDEWgtnx6ufg=
  - secure: BjiDy8irdLJtZIFuC3ValCP8P+txBROtCW/TZ9Cg1dmcaRTcv5H0lWUvPrJume0kQvNnN195ViRDqDKGxvQpjhBTG3YWcHEMIGqZyWgOGSXSYuBVbN4eS4nZxfAjocubpF/QTnQ/9haXTeF1ySUVoRXqymM26ONrze1aeBiuL+O15eHB0eYcQkZu3GT8iiYaGryFvg1/mPYb95/2eSmidXKVdbE8fIglAQFgejA6XBT5YnmTRG7EO5lA12zcIMUYfM5qKcoFFSEUnBYWgPMDQO1+uI6VJ7WVXqHZFZDLW/ZFtlRfCwx6CJczkCsq5XrlW0N4UzWDUB4emOwzxEt+NEWjfPsDLwFqrdvi1uMHNreon7SezGTxQEyyJPMIn9PMSErk91FRbBTC09fl1/YhB9CttTOBx4tvvRXwd/A7iL/q64gXB+lmn0Y/gf9jh0ivZKG2X3tAoDhMtSp9n3X1XzeZRAZVt5+g9PYZev7IlzYkjbIfJwILZSq09uCgom1EMfAr+gcgRqRkftxn7XLZhD5lWEeXrU4UWn+yefJtcWpZ93Yxwa9yhMHIxFbdDyyxVCfSgo85Xtq0RnmgJJG3Jv/EoA89563WysSAyvMDOMi9hYLjN+Ai38/FlmJntDtCYkm+syHBRqlyhXvPl5BszVpOGgW0Z7mXtTDfflzBebA=
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=tepxi/lates
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
